/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VisaRouteImport } from './routes/visa'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ReligiousRouteImport } from './routes/religious'
import { Route as PlanTripRouteImport } from './routes/plan-trip'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as CorporateRouteImport } from './routes/corporate'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'

const VisaRoute = VisaRouteImport.update({
  id: '/visa',
  path: '/visa',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ReligiousRoute = ReligiousRouteImport.update({
  id: '/religious',
  path: '/religious',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanTripRoute = PlanTripRouteImport.update({
  id: '/plan-trip',
  path: '/plan-trip',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const CorporateRoute = CorporateRouteImport.update({
  id: '/corporate',
  path: '/corporate',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/corporate': typeof CorporateRoute
  '/gallery': typeof GalleryRoute
  '/plan-trip': typeof PlanTripRoute
  '/religious': typeof ReligiousRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/visa': typeof VisaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/corporate': typeof CorporateRoute
  '/gallery': typeof GalleryRoute
  '/plan-trip': typeof PlanTripRoute
  '/religious': typeof ReligiousRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/visa': typeof VisaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/corporate': typeof CorporateRoute
  '/gallery': typeof GalleryRoute
  '/plan-trip': typeof PlanTripRoute
  '/religious': typeof ReligiousRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/visa': typeof VisaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/corporate'
    | '/gallery'
    | '/plan-trip'
    | '/religious'
    | '/sitemap.xml'
    | '/visa'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/corporate'
    | '/gallery'
    | '/plan-trip'
    | '/religious'
    | '/sitemap.xml'
    | '/visa'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/corporate'
    | '/gallery'
    | '/plan-trip'
    | '/religious'
    | '/sitemap.xml'
    | '/visa'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  CorporateRoute: typeof CorporateRoute
  GalleryRoute: typeof GalleryRoute
  PlanTripRoute: typeof PlanTripRoute
  ReligiousRoute: typeof ReligiousRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  VisaRoute: typeof VisaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/visa': {
      id: '/visa'
      path: '/visa'
      fullPath: '/visa'
      preLoaderRoute: typeof VisaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/religious': {
      id: '/religious'
      path: '/religious'
      fullPath: '/religious'
      preLoaderRoute: typeof ReligiousRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plan-trip': {
      id: '/plan-trip'
      path: '/plan-trip'
      fullPath: '/plan-trip'
      preLoaderRoute: typeof PlanTripRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/corporate': {
      id: '/corporate'
      path: '/corporate'
      fullPath: '/corporate'
      preLoaderRoute: typeof CorporateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  CorporateRoute: CorporateRoute,
  GalleryRoute: GalleryRoute,
  PlanTripRoute: PlanTripRoute,
  ReligiousRoute: ReligiousRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  VisaRoute: VisaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
